# This file was generated by GoReleaser. DO NOT EDIT.
cask "beeper-desktop-cli" do
  name "beeper-desktop-cli"
  desc "CLI for Beeper Desktop API"
  homepage "https://developers.beeper.com/desktop-api/"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beeper-desktop-cli"
  manpage "man/man1/beeper-desktop-cli.1.gz"
  bash_completion "completions/beeper-desktop-cli.bash"
  zsh_completion "completions/beeper-desktop-cli.zsh"
  fish_completion "completions/beeper-desktop-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_macos_amd64.zip"
      sha256 "7b960bcd2f20460f2136da3ab46486d2c32849850fcca862d095248ed5a30cd2"
    end
    on_arm do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_macos_arm64.zip"
      sha256 "1fae4467b16391007259ab85aa2002fc748480e0100c52667703f26a389b5af0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_linux_amd64.tar.gz"
      sha256 "0a205363cd5db346a70551bf513b04dbbdc6be4309df7e5bfe5202e69eaa43b6"
    end
    on_arm do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_linux_arm64.tar.gz"
      sha256 "c05403ca6bce402aac39f580f58d3a1c180cb25b8ab31e115d4e8a2d030ffbde"
    end
  end

  # No zap stanza required
end
