# This file was generated by GoReleaser. DO NOT EDIT.
cask "beeper-desktop-cli" do
  name "beeper-desktop-cli"
  desc "CLI for Beeper Desktop API"
  homepage "https://developers.beeper.com/desktop-api/"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beeper-desktop-cli"
  manpage "man/man1/beeper-desktop-cli.1.gz"
  bash_completion "completions/beeper-desktop-cli.bash"
  zsh_completion "completions/beeper-desktop-cli.zsh"
  fish_completion "completions/beeper-desktop-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_macos_amd64.zip"
      sha256 "1c5c8d51f3c84c52c6f20e5bad26ecaadae375363146613919f2afb7fe8cbe9a"
    end
    on_arm do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_macos_arm64.zip"
      sha256 "5762f33fa4948b793dce2b2087a840422c3f52a208b40c03dd75f1dc8dabcb89"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_linux_amd64.tar.gz"
      sha256 "c5b9e0088f166c2d776892774cb3dcfcd8952888ea7043478ec74f2610ea9c21"
    end
    on_arm do
      url "https://github.com/beeper/desktop-api-cli/releases/download/v#{version}/beeper-desktop-cli_#{version}_linux_arm64.tar.gz"
      sha256 "328dfc9e5b85d9090fbd1cbedfcaadb341bb59187a4fab109e9dafc8b7b05ae8"
    end
  end

  # No zap stanza required
end
